In [41]:
import numpy as np
ary = np.zeros((14, 14)).astype(int)

ary[0] = np.arange(0, 14)
print(ary)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [42]:
for i in range(14):
    ary[1][i] = sum(ary[0][:i+1])
print(ary)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 0  1  3  6 10 15 21 28 36 45 55 66 78 91]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [43]:
for i in range(1, 14):
    for j in range(1, 14):
        ary[i][j] = sum(ary[i-1][:j+1])
print(ary)

[[      0       1       2       3       4       5       6       7       8
        9      10      11      12      13]
 [      0       1       3       6      10      15      21      28      36
       45      55      66      78      91]
 [      0       1       4      10      20      35      56      84     120
      165     220     286     364     455]
 [      0       1       5      15      35      70     126     210     330
      495     715    1001    1365    1820]
 [      0       1       6      21      56     126     252     462     792
     1287    2002    3003    4368    6188]
 [      0       1       7      28      84     210     462     924    1716
     3003    5005    8008   12376   18564]
 [      0       1       8      36     120     330     792    1716    3432
     6435   11440   19448   31824   50388]
 [      0       1       9      45     165     495    1287    3003    6435
    12870   24310   43758   75582  125970]
 [      0       1      10      55     220     715    2002    500

In [49]:
T = int(input())
for i in range(T):
    A = int(input())
    B = int(input())
    print(A, B)

2
1
3
1 3
2
4
2 4


In [57]:
import numpy as np
ary = np.zeros((15, 15)).astype(int)

ary[0] = np.arange(0, 15)

for i in range(1, 15):
    for j in range(1, 15):
        ary[i][j] = sum(ary[i-1][:j+1])
print(ary)

ans = []
T = int(input())
for i in range(T):
    A = int(input())
    B = int(input())
    ans.append(ary[A][B])
for i in ans:
    print(i)

[[       0        1        2        3        4        5        6        7
         8        9       10       11       12       13       14]
 [       0        1        3        6       10       15       21       28
        36       45       55       66       78       91      105]
 [       0        1        4       10       20       35       56       84
       120      165      220      286      364      455      560]
 [       0        1        5       15       35       70      126      210
       330      495      715     1001     1365     1820     2380]
 [       0        1        6       21       56      126      252      462
       792     1287     2002     3003     4368     6188     8568]
 [       0        1        7       28       84      210      462      924
      1716     3003     5005     8008    12376    18564    27132]
 [       0        1        8       36      120      330      792     1716
      3432     6435    11440    19448    31824    50388    77520]
 [       0        1 

In [87]:
import numpy as np
def whatFloor(A, B):
    ary = np.zeros((A+1, B+1)).astype(int)

    ary[0] = np.arange(0, B+1)

    for i in range(1, A+1):
        for j in range(B+1):
            ary[i][j] = sum(ary[i-1][:j+1])
    return ary[A][B]

T = int(input())
for i in range(T):
    A = int(input())
    B = int(input())
    print(whatFloor(A, B))

1
0
0
0


In [62]:
np.arange(0, 4)

array([0, 1, 2, 3])

In [86]:
Case = input()
for _ in range(int(Case)):
    k = int(input())
    n = int(input())
    num = [i for i in range(1, n + 1)]
    for _ in range(k):
        for j in range(1, n):
            num[j] += num[j-1]
    print(num[-1])

1
0
0


IndexError: list index out of range