# 03 **넘파이**

In [0]:
import numpy as np

### 넘파이 ndarray 개요

넘파이의 기반 데이터 타입은 `ndarray`.
- `ndarray`을 이용해 다차원 배열을 생성하고 다양한 연산을 수행할 수 있다.

넘파이 `array()` 함수는 파이썬의 리스트를 입력 받아 `ndarray`로 변환하는 기능을 수행한다.
- `ndarray` 배열의 `shape` 변수는 `ndarray`의 크기를 튜플 형태로 가지고 있다.

In [12]:
array1 = np.array([1, 2, 3])  # 리스트를 input으로 받음.
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)


array1의 `shape`은 `(3, )`. 1차원 array임을 뜻한다.
<br><br>

In [13]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)


array2의 `shape`은 `(2, 3)`. 2차원 array임을 뜻한다.
<br><BR>

In [14]:
array3 = np.array([[1, 2, 3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


array3의 `shape`은 `(1, 3)`. 2차원 array임을 뜻하는데,
- array1은 명확하게 1차원임을 `(3, )` 형태로 표현했고,
- array3 역시 `(1, 3)`으로 2차원 데이터임을 표현했다.

이 차이를 이해하는 것은 매우 중요하다.
- ML 프로세스를 진행하다 보면 명확히 1차원 또는 다차원 데이터를 요구하는 경우가 있는데, 차원이 달라 오류가 발생하는 경우가 빈번하다.
- 차원의 차수변환 방법을 알아야 이런 오류를 막을 수 있다. 나중에 `reshape()` 때 다시 짚고 넘어가자. 

### ndarray의 데이터 타입

ndarray내 데이터값은 숫자, 문자열 불 등 모두 가능하다. 하지만 한 개의 ndarray 객체에 같은 데이터 타입만 가능하다.
- 다른 데이터 유형이 섞여 있는 리스트를 `ndarray`로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [15]:
lst = [1, 2, 'test']
array = np.array(lst)
print(array, array.dtype)

['1' '2' 'test'] <U21


In [16]:
lst = [1, 2, 3.0]
array = np.array(lst)
print(array, array.dtype)

[1. 2. 3.] float64


int와 string이 섞여 있다면 string으로, int와 float이 섞여 있으면 float으로 변환된다.
- `astype()` 메서드로 `ndarray` 내 데이터 타입 변경이 가능하다. 보통 메모리를 절약해야 할 때 사용한다.

### ndarray를 편리하게 생성하기 - arange, zeros, ones

특정 크기와 차원을 가진 `ndarray`를 연속값이나 0또는 1로 초기화해 생성해야할 때가 있다. 그럴 때 필요한 함수들이다.

`arange()` 함수는 `range()`와 유사하다. 
- 쉽게 생각하면 array를 `range()`로 표현하는 것이다.
- `range()`와 유사하게 start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있다.

In [17]:
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


`zeros()`와 `ones()` 함수는 튜플 형태의 `shape` 값을 입력하면 각각 모든 값을 0과 1로 채운 `ndarray`를 반환한다.
- 함수 인자로 `dtype` 정하지 않으면 float64 형의 데이터로 `ndarray`를 채운다.

In [18]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [19]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

`reshape()` 메서드는 `ndarray`를 특정 차원 및 크기로 변환한다. 변환을 원하는 크기를 함수 인자로 부여하면 된다.

In [20]:
array = np.arange(10)
print('array:\n', array)

array:
 [0 1 2 3 4 5 6 7 8 9]


In [21]:
array2 = array.reshape(2, 5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
array3 = array.reshape(5, 2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


`reshape()`은 지정된 사이즈로 변경할 수 없다면 오류를 발생한다.

In [23]:
#array.reshape(4, 3)

'''
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-bab7effd8b9b> in <module>()
----> 1 array.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)
'''

'\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-21-bab7effd8b9b> in <module>()\n----> 1 array.reshape(4, 3)\n\nValueError: cannot reshape array of size 10 into shape (4,3)\n'

`reshape()`를 실전에서 더욱 효율적으로 사용하는 경우는 인자로 -1을 적용하는 경우.
- -1을 인자로 사용하면 `ndarray`와 호환되는 새로운 `shape`으로 변환한다.

In [24]:
array = np.arange(10)
print(array)
array2 = array.reshape(-1, 5)  # 10개의 데이터를 2개의 row, 5개의 column에 할당.
print('array2 shape:', array2.shape)
array3 = array.reshape(5, -1)  # 10개의 데이터를 5개의 row, 2개의 column에 할당.
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


-1인자는 `reshape(-1, 1)`와 같은 형태로 자주 사용된다. 
- `reshape(-1, 1)`은 원본 `ndarray`가 어떤 형태라도 다수의 row와 오직 1개의 column을 가진 2차원 `ndarray`로 변환한다.
- 여러 개의 `ndarray`는 `stack`이나 `concat`으로 결합할 때 각각의 `ndarray`의 형태를 통일해 유용하게 사용된다.

> `ndarray`는 `tolist()` 메서드를 이용해 리스트 자료형으로 변환할 수 있다. 
> - 리스트를 `print`했을 때 더 이해하기 쉬워 `ndarray`를 리스트로 변환해 출력한다.

In [25]:
array = np.arange(8)
array3d = array.reshape((2, 2, 2))
print('array3d without tolist():\n', array3d)
print('\narray3d:\n',array3d.tolist())

array3d without tolist():
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [26]:
# 3차원 ndarray를 2차원 ndarray로 변환.
array2d = array3d.reshape(-1, 1)
print('array2d:\n',array2d.tolist())
print('array2d shape:', array2d.shape)

array2d:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array2d shape: (8, 1)


In [27]:
# 1차원 ndarray를 2차원 ndarray로 변환.
array2d = array.reshape(-1, 1)
print('array2d:\n', array2d.tolist())
print('array2d shape:', array2d.shape)

array2d:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array2d shape: (8, 1)


### 인덱싱(Indexing)

##### **단일 값 추출**

1개의 데이터값을 선택하려면 `ndarray` 객체에 해당하는 위치의 인덱스 값을 `[]` 안에 입력하면 된다.

In [28]:
array = np.arange(start=1, stop=10)
print('array:',array)
value1 = array[2]
print('value1:', value1)
value2 = array[-2]
print('value2:', value2)

array: [1 2 3 4 5 6 7 8 9]
value1: 3
value2: 8


다차원 `ndarray`에서 단일 값을 추출하는 방법은 좌표를 입력하는 것이라 생각하자.

In [29]:
array = np.arange(start=1, stop=10)
array2d = array.reshape(3, 3)
print(array2d)

print('(row=0, col=0):', array2d[0, 0])
print('(row=2, col=0):', array2d[2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0): 1
(row=2, col=0): 7


주목해야 할 부분은 axis0과 axis1. 
- axis0은 로우 방향, axis1은 컬럼 방향의 축을 의미한다. **로우와 컬럼은 `ndarray`에서는 사용되는 않는 방식이다**.
- 2차원이므로 axis0, axis1으로 구분되고 3차원은 axis0, axis1, axis2, 총 3개의 축을 가지게 된다.

axis0이 로우 방향, axis1이 컬럼 방향 축임을 이해하는 것은 중요하다.
- 다차원 `ndarray`의 경우 축(axis)에 따른 연산을 지원하기 때문이다.

##### **슬라이싱**

단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 `ndarray` 타입.

In [30]:
array = np.arange(start=1, stop=10)
array2 = array[0:3]
print(array2)
print(type(array2))

[1 2 3]
<class 'numpy.ndarray'>


2차원 `ndarray`에서의 슬라이싱도 1차원과 유사하다.
- 콤마(,)로 로우와 컬럼 인덱스를 지칭하는 부분만 다르다.

In [31]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n:', array2d)
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])

array2d:
: [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]


##### **팬시 인덱싱**

리스트나 `ndarray`로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 `ndarray`를 반환하는 인덱싱 방식. 팬시하진 않음.

In [32]:
array = np.arange(1, 10).reshape(3, 3)
print('array:\n', array)
array1 = array[[0, 1], 0:1]
print('array1:\n', array1)

array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array1:
 [[1]
 [4]]


##### **불린 인덱싱**

조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용된다. 
- `ndarray`의 인덱스를 지정하는 `[]` 내에 조건문을 기재하면 된다.

In [33]:
array1d = np.arange(1, 10)
array2 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:', array2)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

행렬을 정렬하는 `np.sort()`와 `ndarray.sort()`, 그리고 정렬된 행렬의 인덱스를 반환하는 `argsort()`에 대해 알아보자.

##### **행렬 정렬**

`np.sort()`는 넘파이에서 `sort()`를 호출하는 방식.
- `np.sort()`의 경우 원 행렬은 유지한 채 원 행렬의 정렬된 행렬을 반환한다.

`ndarray.sort()`는 행렬 자체에서 `sort()`를 호출하는 방식.
- `ndarray.sort()`는 원 행렬 자체를 정렬한 형태로 변환하고 반환 값은 `None`.

> `ndarray.sort()`은 기존 행렬이 변경되고, `np.sort()` 새로운 행렬을 생성한다.

In [39]:
org_array = np.array([3, 1, 9, 5])
print("원본 행렬:", org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)  # np.sort()로 정렬했으므로 기존 행렬에는 변화가 없다.

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('\norg_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)  # 원본 행렬이 정렬됐다.

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


내림차순을 적용하기 위해선 기존 공식에 `[::-1]`을 적용하면 된다.

In [40]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우, 컬럼 방향으로 정렬을 수행할 수 있다.

In [44]:
array2d = np.array([[8, 12],
                    [7, 1]])
print('원 행렬:\n', array2d)
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

원 행렬:
 [[ 8 12]
 [ 7  1]]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


##### **정렬된 행렬의 인덱스를 반환하기**

원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 `np.argsort()`를 이용한다.
- `np.argsort()`는 정렬 행렬의 원본 행렬 인덱스를 `ndarray` 형으로 반환한다.

In [47]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스:", sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


내림차순으로 정렬시 위와 같이 `[::-1]`을 적용하면 된다.

In [48]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


`argsort()`는 넘파이에서 활용도가 매우 높다. 
- `ndarray`는 판다스 DataFrame같은 메타 데이터를 가질 수 없다. 그래서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 `ndarray`로 가져야 한다.

예를 들어 학생별 시험 성적을 데이터로 표현하기 위해선 이름과 성적을 각각 `ndarray`로 가져야 한다.
- John=78, Mike=95, Sarah=84를 `ndarray`로 활용하고자 한다면 `name=['John', 'Mike', 'Sarah']`와 `score=[78, 95, 84]`와 같이 2개의 `ndarray`가 필요하다.
- 이 때 성적순으로 이름을 출력하고자 한다면 `np.argsort(score)`로 반환된 인덱스를 `name`에 팬시 인덱스를 적용해 추출할 수 있다.

In [53]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score)
print('성적 오름차순 정렬 score의 인덱스: ', sort_indices_asc)
print('성적 오름차순으로 name의 이름 출력:', name[sort_indices_asc])

성적 오름차순 정렬 score의 인덱스:  [0 2 4 1 3]
성적 오름차순으로 name의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

넘파이는 다양한 선형대수 연산을 지원하는데, 그 중 가장 많이 사용되는 행렬 내적과 전치 행렬을 구하는 방법을 알아보자.

##### **행렬 내적(행렬 곱)**

두 행렬 A와 B의 내적은 `np.dot()`을 이용해 계산이 가능하다.

In [54]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


##### **전치 행렬**

넘파이의 `transpose()`를 통해 전치 행렬을 쉽게 구할 수 있다.

In [56]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A 행렬:\n', A)
print('A의 전치 행렬:\n', transpose_mat)

A 행렬:
 [[1 2]
 [3 4]]
A의 전치 행렬:
 [[1 3]
 [2 4]]


# 04 **데이터 핸들링 - 판다스**

In [0]:
import pandas as pd

### Kaggle setup

In [70]:
# 코랩에서 Kaggle 실행
!pip install kaggle
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"tjdrms2023","key":"420f91d78b4ea1dbbe26e3078903b138"}'}

In [71]:
# 파일 제대로 업로드됐는지 확인하기.
ls -1ha kaggle.json

kaggle.json


In [72]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
# Permission Warning 이 일어나지 않도록 
!chmod 600 ~/.kaggle/kaggle.json
# 본인이 참가한 모든 대회 보기 
!kaggle competitions list

ref                                               deadline             category            reward  teamCount  userHasEntered  
------------------------------------------------  -------------------  ---------------  ---------  ---------  --------------  
digit-recognizer                                  2030-01-01 00:00:00  Getting Started  Knowledge       2232           False  
titanic                                           2030-01-01 00:00:00  Getting Started  Knowledge      17344            True  
house-prices-advanced-regression-techniques       2030-01-01 00:00:00  Getting Started  Knowledge       4617            True  
connectx                                          2030-01-01 00:00:00  Getting Started  Knowledge        299           False  
nlp-getting-started                               2030-01-01 00:00:00  Getting Started      Kudos       3170           False  
competitive-data-science-predict-future-sales     2020-12-31 23:59:00  Playground           Kudos       6124   

In [73]:
# 타이타닉 데이터 불러오기
! kaggle competitions download -c titanic

  0% 0.00/59.8k [00:00<?, ?B/s]
100% 59.8k/59.8k [00:00<00:00, 51.3MB/s]
  0% 0.00/3.18k [00:00<?, ?B/s]
100% 3.18k/3.18k [00:00<00:00, 3.01MB/s]
  0% 0.00/28.0k [00:00<?, ?B/s]
100% 28.0k/28.0k [00:00<00:00, 28.4MB/s]


In [74]:
# 불러온 데이터 확인하기
!ls

gender_submission.csv  kaggle.json  sample_data  test.csv  train.csv


In [75]:
# 필요한 파일 압축 풀기
# !unzip ___

Archive:  train.csv
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of train.csv or
        train.csv.zip, and cannot find train.csv.ZIP, period.


### 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

판다스는 다양한 포맷으로 된 파일을 DataFrame으로 로딩할 수 있는 편리한 API를 제공한다.
- 대표적으로 `read_csv()`, `read_table()`, `read_fwf()`가 있다.
- `read_table()`과 `read_csv()`의 가장 큰 차이는 Delimiter가 콤마(,)냐 탭(\t)이냐의 차이.
- `read_fwf()`는 Fixed Width(고정 길이 기반) 포맷을 DataFrame으로 로딩하기 위한 API.

In [80]:
titanic_df = pd.read_csv('train.csv')
titanic_df.head(5)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [81]:
titanic_df.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

Pclass 컬럼이 어떠한 분포로 구성되어 있는지 살펴보자.
- `value_counts()` 메서드를 호출하면 해당 칼럼값의 유형과 건수를 확인할 수 있다. 
- `value_counts()`는 Series에서만 가능하다. DataFrame은 지원하지 않는다.

In [82]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

DataFrame의 `[]` 연산자 내부에 칼럼명을 입력하면 해당 칼럼에 해당하는 Series 객체를 반환한다.

In [83]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


Series는 Index와 단 하나의 칼럼으로 구성된 데이터 세트.
- Index는 단순히 숫자 값과 같은 의미 없는 식별자만 할당하는 것이 아니라 고유성이 보장되면 의미 있는 데이터값 할당도 가능하다.
- 아래의 경우 칼럼 값별 데이터 건수를 반환하므로 고유 칼럼 값을 식별자로 사용할 수 있다.

In [84]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

기본적으로 DataFrame은 리스트, 딕셔너리, 그리고 `ndarray` 등 다양한 데이터로부터 생성될 수 있다.
- 반대로 리스트, 딕셔너리, `ndarray`로 변환될 수 있다.
- 특히 사이킷런의 많은 API들은 `ndarray`를 입력 인자로 사용하는 경우가 대부분이다.

##### **ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기**