In [1]:
import numpy as np

<br><br>
# np.argsort
입력된 리스트의 value의 크기 순서대로 해당 인덱스를 나열.

In [4]:
# 예제
lst = [0.18021379, 0.22216499, 0.00547777, 0.15400408, 0.01561225,
       0.02026274, 0.01321328, 0.00080988, 0.00365953, 0.03224953,
       0.00594731, 0.00682391, 0.12589197]
np.argsort(lst)

array([ 7,  8,  2, 10, 11,  6,  4,  5,  9, 12,  3,  0,  1])

<br><br>
# np.ravel()
다차원 배열을 평평하게 1차원 배열로 만들어줌.

In [2]:
# 예제
lst = np.arange(12).reshape(3, 4)  # 먼저 3x4 matrix 생성.
lst

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
lst = lst.ravel()
lst

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])